### PR TITLE
Make obus safe-string compatible

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by diml** [comment]
@steinuil @talex5 @jpdeplaix I just saw your PRs. I haven't worked on obus in years and I'm not planning to do any more work on it. Is one of you interested in taking over the maintenance of the project?

**Comment by jpdeplaix** [comment]
I'm not really interested because I'm not using it and I even don't know what it does.
@talex5 oops, sorry I forgot to check the existing PRs. There are some differences but it's a bit redundant. Sorry :(

**Comment by talex5** [comment]
I use it for 0install, so I intend to try to keep it working. If you give me commit access, I'll happily merge my own PR. I don't have any plans to improve it apart from that though.

**Comment by diml** [comment]
@talex5 sounds good to me, I've sent you an invite

**Comment by talex5** [comment]
@diml thanks! Could you also go to https://travis-ci.org and enable Travis tests for this repository?

(if you don't use Travis, it should just be a case of logging in with your GitHub account and flicking the toggle on the accounts page)

**Comment by diml** [comment]
@talex5 sure, done

**Comment by talex5** [comment]
Thanks - that works!

**Comment by jpdeplaix** [comment]
Is there any plan to do a release soon ?

**Pull request closed without merging**
